[package]
name = "cell-generator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy-arms = {git = "https://github.com/pseuxide/toy-arms", features = ["external"]}
